{
  "version": 1,
  "build": {
    "command": "npm install && npm run build",
    "cwd": "/",
    "publish": "dist",
    "environment": {
      "NODE_VERSION": "18"
    }
  },
  "preview": {
    "command": "npm install && npm run build",
    "cwd": "/",
    "publish": "dist"
  }
}
